version: "2.1"
services:
  duplicati:
    image: ghcr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000 # The PUID can be set to 0 which will give root permissions to the container
      - PGID=1000  # The PGID can be set to 0 which will give root permissions to the container
      - TZ=Europe/Berlin # Set the appropriate timezone https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
    volumes:
      - ./config:/customDirs/config # Volume Mount to the config folder of all your docker containers
      - ./backups:/customDirs/backups # If the backup needs to be stored on your machine, add a volume mount to that path here
      - /share/test:/customDirs/tobackup/test:ro # Volume Mount to the folder that needs to backed up
      - ./restore:/customDirs/restore # To be able to restore files directly on the file system
      - ./torestore:/customDirs/torestore # To be able to put files to restore directly to the file system
      - /share/pricetracker/live/priceTracker/install/database/backup:/customDirs/tobackup/priceTracker:ro # Volume Mount to the pricetracker database backup to allow making backup of this directory
      - /share/namedCountdown/live/nameTheCountdown/install/database/backup:/customDirs/tobackup/nameTheCountdown:ro # Volume Mount to the namethecountdownbot database backup to allow making backup of this directory
    ports:
      - 8200:8200
    restart: unless-stopped
